name: Schedule Test

on:
  workflow_dispatch:
  schedule:
    - cron: "17,32,47,59 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger
        run: |
          echo "Triggered by ${{ github.event_name }}"
          date -u
